apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat-pdb
  namespace: zhujq
spec:
  selector:
    matchLabels:
      app: wechat-pdb
  replicas: 1
  template:
    metadata:
      labels:
        app: wechat-pdb
    spec:
      containers:
        - name: wechat-pdb
          image: zhujq/wechat
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi

apiVersion: v1
kind: Service
metadata:
  annotations:
    dev.okteto.com/auto-ingress: "true"
  name: wechat-pdb
  namespace: zhujq
  labels:
    name: wechat-pdb
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: wechat-pdb
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray
  namespace: zhujq
spec:
  selector:
    matchLabels:
      app: v2ray
  replicas: 1
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      containers:
        - name: v2ray
          image: zhujq/ibmray
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 64Mi

apiVersion: v1
kind: Service
metadata:
  annotations:
    dev.okteto.com/auto-ingress: "true"
  name: v2ray
  namespace: zhujq
  labels:
    name: v2ray
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: v2ray


